version: "3.8"

services:
  database:
    build: ../../../saleslist-backend/database
    container_name: saleslist-database-dev
    environment:
      POSTGRES_DB: social_navigator
      POSTGRES_USER: social_navigator_user
      POSTGRES_PASSWORD: social_navigator_password
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - saleslist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_navigator_user -d social_navigator"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../../saleslist-backend
      dockerfile: Dockerfile
    container_name: saleslist-backend-dev
    env_file:
      - ../../env/dev/backend.env
    ports:
      - "8010:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - saleslist-network
    volumes:
      - ../../../saleslist-backend:/app
    command: >
      bash scripts/run-dev.sh

  frontend:
    build:
      context: ../../../saleslist-front
      dockerfile: Dockerfile.dev
    container_name: saleslist-frontend-dev
    env_file:
      - ../../env/dev/frontend.env
    ports:
      - "3010:3000"
    volumes:
      - ../../../saleslist-front:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - saleslist-network
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:

networks:
  saleslist-network:
    driver: bridge
