version: "3.8"

services:
  database:
    build: ../saleslist-backend/database
    container_name: saleslist-database
    environment:
      POSTGRES_DB: social_navigator
      POSTGRES_USER: social_navigator_user
      POSTGRES_PASSWORD: social_navigator_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saleslist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_navigator_user -d social_navigator"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../saleslist-backend
      dockerfile: Dockerfile
    container_name: saleslist-backend
    env_file:
      - ../env/prod/backend.env
    ports:
      - "8002:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - saleslist-network
    volumes:
      - ../saleslist-backend:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python seed_data.py &&
        gunicorn --bind 0.0.0.0:8000 --reload saleslist_backend.wsgi:application
      "

  frontend:
    build:
      context: ../saleslist-front
      dockerfile: Dockerfile.simple
    container_name: saleslist-frontend
    env_file:
      - ../env/prod/frontend.env
    ports:
      - "3002:3000"
    volumes:
      - ../saleslist-front:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - saleslist-network

volumes:
  postgres_data:

networks:
  saleslist-network:
    driver: bridge
