name: Merge develop to main

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  merge-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge develop to main
        run: |
          git checkout main
          git pull origin main
          git merge origin/develop --no-ff -m "Merge develop for release ${{ github.event.inputs.version }}"
          git push origin main

      - name: Create and push tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Trigger release workflow
        run: |
          echo "🚀 Release ${{ github.event.inputs.version }} tagged and will be deployed to production"